<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__DemandeContact__CLASSMETADATA__' => 0,
'App__Entity__Projet__CLASSMETADATA__' => 1,
'App__Entity__ProjetImage__CLASSMETADATA__' => 2,
'App__Entity__Technologie__CLASSMETADATA__' => 3,
'App__Entity__Utilisateur__CLASSMETADATA__' => 4,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\DemandeContact',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DemandeContactRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'email' => $o[3],
                    'message' => $o[4],
                    'dateEnvoi' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id_contact' => 'id',
                    'nom' => 'nom',
                    'email' => 'email',
                    'message' => 'message',
                    'date_envoi' => 'dateEnvoi',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_contact',
                    'nom' => 'nom',
                    'email' => 'email',
                    'message' => 'message',
                    'dateEnvoi' => 'date_envoi',
                ],
            ],
            'table' => [
                [
                    'name' => 'demande_contact',
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\DemandeContact',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'email',
                'message',
                'dateEnvoi',
            ],
            'columnName' => [
                1 => 'id_contact',
                'nom',
                'email',
                'message',
                'date_envoi',
            ],
            'length' => [
                2 => 100,
                255,
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Projet',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProjetRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'titre' => $o[2],
                    'description' => $o[3],
                    'dateDebut' => $o[4],
                    'dateFin' => $o[5],
                    'visible' => $o[6],
                    'lien' => $o[7],
                    'image' => $o[8],
                    'documents' => $o[9],
                    'githubLinks' => $o[10],
                    'typeProjet' => $o[11],
                    'etat' => $o[12],
                ],
            ],
            'fieldNames' => [
                [
                    'id_projet' => 'id',
                    'titre' => 'titre',
                    'description' => 'description',
                    'date_debut' => 'dateDebut',
                    'date_fin' => 'dateFin',
                    'visible' => 'visible',
                    'lien' => 'lien',
                    'image' => 'image',
                    'documents' => 'documents',
                    'github_links' => 'githubLinks',
                    'type_projet' => 'typeProjet',
                    'etat' => 'etat',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_projet',
                    'titre' => 'titre',
                    'description' => 'description',
                    'dateDebut' => 'date_debut',
                    'dateFin' => 'date_fin',
                    'visible' => 'visible',
                    'lien' => 'lien',
                    'image' => 'image',
                    'documents' => 'documents',
                    'githubLinks' => 'github_links',
                    'typeProjet' => 'type_projet',
                    'etat' => 'etat',
                ],
            ],
            'table' => [
                [
                    'name' => 'projet',
                ],
            ],
            'associationMappings' => [
                [
                    'projetImages' => $o[13],
                    'technologies' => $o[14],
                ],
            ],
            'idGenerator' => [
                $o[18],
            ],
            'name' => [
                'App\\Entity\\Projet',
                15 => 'projet_technologie',
                'id_projet',
                'id_technologie',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'date',
                'date',
                'boolean',
                'string',
                'string',
                'text',
                'text',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'titre',
                'description',
                'dateDebut',
                'dateFin',
                'visible',
                'lien',
                'image',
                'documents',
                'githubLinks',
                'typeProjet',
                'etat',
            ],
            'columnName' => [
                1 => 'id_projet',
                'titre',
                'description',
                'date_debut',
                'date_fin',
                'visible',
                'lien',
                'image',
                'documents',
                'github_links',
                'type_projet',
                'etat',
            ],
            'length' => [
                2 => 255,
                7 => 255,
                255,
                11 => 50,
                50,
            ],
            'nullable' => [
                4 => true,
                true,
                7 => true,
                true,
                true,
                true,
                true,
                true,
                16 => false,
                false,
            ],
            'cascade' => [
                13 => [
                    'remove',
                ],
            ],
            'fetch' => [
                13 => 2,
                2,
            ],
            'orphanRemoval' => [
                13 => true,
            ],
            'sourceEntity' => [
                13 => 'App\\Entity\\Projet',
                'App\\Entity\\Projet',
            ],
            'mappedBy' => [
                13 => 'projet',
            ],
            'inversedBy' => [
                14 => 'projets',
            ],
            'joinTable' => [
                14 => $o[15],
            ],
            'joinTableColumns' => [
                14 => [
                    'id_projet',
                    'id_technologie',
                ],
            ],
            'relationToSourceKeyColumns' => [
                14 => [
                    'id_projet' => 'id_projet',
                ],
            ],
            'relationToTargetKeyColumns' => [
                14 => [
                    'id_technologie' => 'id_technologie',
                ],
            ],
            'joinColumns' => [
                15 => [
                    $o[16],
                ],
            ],
            'inverseJoinColumns' => [
                15 => [
                    $o[17],
                ],
            ],
            'deferrable' => [
                16 => false,
                false,
            ],
            'unique' => [
                16 => false,
                false,
            ],
            'referencedColumnName' => [
                16 => 'id_projet',
                'id_technologie',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                13 => 'projetImages',
                'technologies',
            ],
            'targetEntity' => [
                13 => 'App\\Entity\\ProjetImage',
                'App\\Entity\\Technologie',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ProjetImage',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProjetImageRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'imagePath' => $o[2],
                ],
            ],
            'fieldNames' => [
                [
                    'id_image' => 'id',
                    'image_path' => 'imagePath',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_image',
                    'imagePath' => 'image_path',
                ],
            ],
            'table' => [
                [
                    'name' => 'projet_images',
                ],
            ],
            'associationMappings' => [
                [
                    'projet' => $o[3],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\ProjetImage',
                4 => 'id_projet',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'imagePath',
            ],
            'columnName' => [
                1 => 'id_image',
                'image_path',
            ],
            'length' => [
                2 => 255,
            ],
            'fetch' => [
                3 => 2,
            ],
            'sourceEntity' => [
                3 => 'App\\Entity\\ProjetImage',
            ],
            'inversedBy' => [
                3 => 'projetImages',
            ],
            'sourceToTargetKeyColumns' => [
                3 => [
                    'id_projet' => 'id_projet',
                ],
            ],
            'targetToSourceKeyColumns' => [
                3 => [
                    'id_projet' => 'id_projet',
                ],
            ],
            'joinColumns' => [
                3 => [
                    $o[4],
                ],
            ],
            'joinColumnFieldNames' => [
                3 => [
                    'id_projet' => 'id_projet',
                ],
            ],
            'deferrable' => [
                4 => false,
            ],
            'unique' => [
                4 => false,
            ],
            'nullable' => [
                4 => false,
            ],
            'referencedColumnName' => [
                4 => 'id_projet',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                3 => 'projet',
            ],
            'targetEntity' => [
                3 => 'App\\Entity\\Projet',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Technologie',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\TechnologieRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'description' => $o[3],
                    'dateDebut' => $o[4],
                    'certificationsPdf' => $o[5],
                    'statut' => $o[6],
                    'categorie' => $o[7],
                    'certified' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id_technologie' => 'id',
                    'nom' => 'nom',
                    'description' => 'description',
                    'date_debut' => 'dateDebut',
                    'certifications_pdf' => 'certificationsPdf',
                    'statut' => 'statut',
                    'categorie' => 'categorie',
                    'certified' => 'certified',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_technologie',
                    'nom' => 'nom',
                    'description' => 'description',
                    'dateDebut' => 'date_debut',
                    'certificationsPdf' => 'certifications_pdf',
                    'statut' => 'statut',
                    'categorie' => 'categorie',
                    'certified' => 'certified',
                ],
            ],
            'table' => [
                [
                    'name' => 'technologie',
                ],
            ],
            'associationMappings' => [
                [
                    'projets' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Technologie',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'date',
                'json',
                'string',
                'string',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'description',
                'dateDebut',
                'certificationsPdf',
                'statut',
                'categorie',
                'certified',
            ],
            'columnName' => [
                1 => 'id_technologie',
                'nom',
                'description',
                'date_debut',
                'certifications_pdf',
                'statut',
                'categorie',
                'certified',
            ],
            'length' => [
                2 => 100,
                6 => 50,
                50,
            ],
            'nullable' => [
                5 => true,
                true,
                true,
            ],
            'fetch' => [
                9 => 2,
            ],
            'sourceEntity' => [
                9 => 'App\\Entity\\Technologie',
            ],
            'mappedBy' => [
                9 => 'technologies',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                9 => 'projets',
            ],
            'targetEntity' => [
                9 => 'App\\Entity\\Projet',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Utilisateur',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UtilisateurRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'email' => $o[4],
                    'motDePasse' => $o[5],
                    'dateCreation' => $o[6],
                    'roles' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id_utilisateur' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'mot_de_passe' => 'motDePasse',
                    'date_creation' => 'dateCreation',
                    'roles' => 'roles',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id_utilisateur',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'motDePasse' => 'mot_de_passe',
                    'dateCreation' => 'date_creation',
                    'roles' => 'roles',
                ],
            ],
            'table' => [
                [
                    'name' => 'utilisateur',
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Utilisateur',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'datetime',
                'json',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'motDePasse',
                'dateCreation',
                'roles',
            ],
            'columnName' => [
                1 => 'id_utilisateur',
                'nom',
                'prenom',
                'email',
                'mot_de_passe',
                'date_creation',
                'roles',
            ],
            'length' => [
                2 => 100,
                100,
                191,
                255,
            ],
            'unique' => [
                4 => true,
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
