<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHIce99\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHIce99/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHHIce99.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHHIce99\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHHIce99\App_KernelProdContainer([
    'container.build_hash' => 'HHIce99',
    'container.build_id' => 'a4e04543',
    'container.build_time' => 1773680829,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHIce99');
