<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RDySncOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rDySncO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projet' => ['privates', '.errored..service_locator.rDySncO.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.rDySncO": it needs an instance of "App\\Entity\\Projet" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'projet' => 'App\\Entity\\Projet',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.rDySncO'])) {
            return $container->privates['.service_locator.rDySncO'];
        }

        return $container->privates['.service_locator.rDySncO'] = $instance;
    }
}
