<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\ContactController::listContactRequests' => ['privates', '.service_locator.LHrctDy.App\\Controller\\Admin\\ContactController::listContactRequests()', 'getContactControllerlistContactRequestsService', true],
            'App\\Controller\\Admin\\ContactController::delete' => ['privates', '.service_locator.B3PwOFX.App\\Controller\\Admin\\ContactController::delete()', 'getContactControllerdeleteService', true],
            'App\\Controller\\Admin\\ContactController::show' => ['privates', '.service_locator.7J_EGIL.App\\Controller\\Admin\\ContactController::show()', 'getContactControllershowService', true],
            'App\\Controller\\Admin\\GalerieController::addImage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::addImage()', 'getGalerieControlleraddImageService', true],
            'App\\Controller\\Admin\\GalerieController::deleteImage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()', 'getGalerieControllerdeleteImageService', true],
            'App\\Controller\\Admin\\GalerieController::index' => ['privates', '.service_locator.BIGH6bh.App\\Controller\\Admin\\GalerieController::index()', 'getGalerieControllerindexService', true],
            'App\\Controller\\Admin\\GalerieController::galerie' => ['privates', '.service_locator.zvDKqz1.App\\Controller\\Admin\\GalerieController::galerie()', 'getGalerieControllergalerieService', true],
            'App\\Controller\\Admin\\ProjectController::list' => ['privates', '.service_locator..tj0HNa.App\\Controller\\Admin\\ProjectController::list()', 'getProjectControllerlistService', true],
            'App\\Controller\\Admin\\ProjectController::create' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\ProjectController::create()', 'getProjectControllercreateService', true],
            'App\\Controller\\Admin\\ProjectController::edit' => ['privates', '.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::edit()', 'getProjectControllereditService', true],
            'App\\Controller\\Admin\\ProjectController::delete' => ['privates', '.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()', 'getProjectControllerdeleteService', true],
            'App\\Controller\\Admin\\TechnologyController::listTechnologies' => ['privates', '.service_locator.zQk5dmt.App\\Controller\\Admin\\TechnologyController::listTechnologies()', 'getTechnologyControllerlistTechnologiesService', true],
            'App\\Controller\\Admin\\TechnologyController::createTechnology' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\TechnologyController::createTechnology()', 'getTechnologyControllercreateTechnologyService', true],
            'App\\Controller\\Admin\\TechnologyController::editTechnology' => ['privates', '.service_locator.TSc3Pz7.App\\Controller\\Admin\\TechnologyController::editTechnology()', 'getTechnologyControllereditTechnologyService', true],
            'App\\Controller\\Admin\\TechnologyController::deleteTechnology' => ['privates', '.service_locator.foA9oWh.App\\Controller\\Admin\\TechnologyController::deleteTechnology()', 'getTechnologyControllerdeleteTechnologyService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.9WZ6zwj.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController::editProfile' => ['privates', '.service_locator.YxhG_3W.App\\Controller\\AdminController::editProfile()', 'getAdminControllereditProfileService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.Kui3vX1.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController::projectsx' => ['privates', '.service_locator.Kui3vX1.App\\Controller\\HomeController::projectsx()', 'getHomeControllerprojectsxService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.5XBlwc3.App\\Controller\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\HomeController::galerie' => ['privates', '.service_locator.5XBlwc3.App\\Controller\\HomeController::galerie()', 'getHomeControllergalerieService', true],
            'App\\Controller\\HomeController::contact' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::contact()', 'getHomeControllercontactService', true],
            'App\\Controller\\HomeController::skills' => ['privates', '.service_locator.ILz2ZmF.App\\Controller\\HomeController::skills()', 'getHomeControllerskillsService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.X6dKtK4.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\ContactController:listContactRequests' => ['privates', '.service_locator.LHrctDy.App\\Controller\\Admin\\ContactController::listContactRequests()', 'getContactControllerlistContactRequestsService', true],
            'App\\Controller\\Admin\\ContactController:delete' => ['privates', '.service_locator.B3PwOFX.App\\Controller\\Admin\\ContactController::delete()', 'getContactControllerdeleteService', true],
            'App\\Controller\\Admin\\ContactController:show' => ['privates', '.service_locator.7J_EGIL.App\\Controller\\Admin\\ContactController::show()', 'getContactControllershowService', true],
            'App\\Controller\\Admin\\GalerieController:addImage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::addImage()', 'getGalerieControlleraddImageService', true],
            'App\\Controller\\Admin\\GalerieController:deleteImage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()', 'getGalerieControllerdeleteImageService', true],
            'App\\Controller\\Admin\\GalerieController:index' => ['privates', '.service_locator.BIGH6bh.App\\Controller\\Admin\\GalerieController::index()', 'getGalerieControllerindexService', true],
            'App\\Controller\\Admin\\GalerieController:galerie' => ['privates', '.service_locator.zvDKqz1.App\\Controller\\Admin\\GalerieController::galerie()', 'getGalerieControllergalerieService', true],
            'App\\Controller\\Admin\\ProjectController:list' => ['privates', '.service_locator..tj0HNa.App\\Controller\\Admin\\ProjectController::list()', 'getProjectControllerlistService', true],
            'App\\Controller\\Admin\\ProjectController:create' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\ProjectController::create()', 'getProjectControllercreateService', true],
            'App\\Controller\\Admin\\ProjectController:edit' => ['privates', '.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::edit()', 'getProjectControllereditService', true],
            'App\\Controller\\Admin\\ProjectController:delete' => ['privates', '.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()', 'getProjectControllerdeleteService', true],
            'App\\Controller\\Admin\\TechnologyController:listTechnologies' => ['privates', '.service_locator.zQk5dmt.App\\Controller\\Admin\\TechnologyController::listTechnologies()', 'getTechnologyControllerlistTechnologiesService', true],
            'App\\Controller\\Admin\\TechnologyController:createTechnology' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\Admin\\TechnologyController::createTechnology()', 'getTechnologyControllercreateTechnologyService', true],
            'App\\Controller\\Admin\\TechnologyController:editTechnology' => ['privates', '.service_locator.TSc3Pz7.App\\Controller\\Admin\\TechnologyController::editTechnology()', 'getTechnologyControllereditTechnologyService', true],
            'App\\Controller\\Admin\\TechnologyController:deleteTechnology' => ['privates', '.service_locator.foA9oWh.App\\Controller\\Admin\\TechnologyController::deleteTechnology()', 'getTechnologyControllerdeleteTechnologyService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.9WZ6zwj.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController:editProfile' => ['privates', '.service_locator.YxhG_3W.App\\Controller\\AdminController::editProfile()', 'getAdminControllereditProfileService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.Kui3vX1.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\HomeController:projectsx' => ['privates', '.service_locator.Kui3vX1.App\\Controller\\HomeController::projectsx()', 'getHomeControllerprojectsxService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.5XBlwc3.App\\Controller\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\HomeController:galerie' => ['privates', '.service_locator.5XBlwc3.App\\Controller\\HomeController::galerie()', 'getHomeControllergalerieService', true],
            'App\\Controller\\HomeController:contact' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::contact()', 'getHomeControllercontactService', true],
            'App\\Controller\\HomeController:skills' => ['privates', '.service_locator.ILz2ZmF.App\\Controller\\HomeController::skills()', 'getHomeControllerskillsService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.X6dKtK4.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\ContactController::listContactRequests' => '?',
            'App\\Controller\\Admin\\ContactController::delete' => '?',
            'App\\Controller\\Admin\\ContactController::show' => '?',
            'App\\Controller\\Admin\\GalerieController::addImage' => '?',
            'App\\Controller\\Admin\\GalerieController::deleteImage' => '?',
            'App\\Controller\\Admin\\GalerieController::index' => '?',
            'App\\Controller\\Admin\\GalerieController::galerie' => '?',
            'App\\Controller\\Admin\\ProjectController::list' => '?',
            'App\\Controller\\Admin\\ProjectController::create' => '?',
            'App\\Controller\\Admin\\ProjectController::edit' => '?',
            'App\\Controller\\Admin\\ProjectController::delete' => '?',
            'App\\Controller\\Admin\\TechnologyController::listTechnologies' => '?',
            'App\\Controller\\Admin\\TechnologyController::createTechnology' => '?',
            'App\\Controller\\Admin\\TechnologyController::editTechnology' => '?',
            'App\\Controller\\Admin\\TechnologyController::deleteTechnology' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminController::editProfile' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::projectsx' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Controller\\HomeController::galerie' => '?',
            'App\\Controller\\HomeController::contact' => '?',
            'App\\Controller\\HomeController::skills' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\ContactController:listContactRequests' => '?',
            'App\\Controller\\Admin\\ContactController:delete' => '?',
            'App\\Controller\\Admin\\ContactController:show' => '?',
            'App\\Controller\\Admin\\GalerieController:addImage' => '?',
            'App\\Controller\\Admin\\GalerieController:deleteImage' => '?',
            'App\\Controller\\Admin\\GalerieController:index' => '?',
            'App\\Controller\\Admin\\GalerieController:galerie' => '?',
            'App\\Controller\\Admin\\ProjectController:list' => '?',
            'App\\Controller\\Admin\\ProjectController:create' => '?',
            'App\\Controller\\Admin\\ProjectController:edit' => '?',
            'App\\Controller\\Admin\\ProjectController:delete' => '?',
            'App\\Controller\\Admin\\TechnologyController:listTechnologies' => '?',
            'App\\Controller\\Admin\\TechnologyController:createTechnology' => '?',
            'App\\Controller\\Admin\\TechnologyController:editTechnology' => '?',
            'App\\Controller\\Admin\\TechnologyController:deleteTechnology' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminController:editProfile' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:projectsx' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'App\\Controller\\HomeController:galerie' => '?',
            'App\\Controller\\HomeController:contact' => '?',
            'App\\Controller\\HomeController:skills' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
