<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerdashboardService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9WZ6zwj.App\Controller\AdminController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9WZ6zwj.App\\Controller\\AdminController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'technologieRepository' => ['privates', 'App\\Repository\\TechnologieRepository', 'getTechnologieRepositoryService', true],
            'demandeContactRepository' => ['privates', 'App\\Repository\\DemandeContactRepository', 'getDemandeContactRepositoryService', true],
            'projetImageRepository' => ['privates', 'App\\Repository\\ProjetImageRepository', 'getProjetImageRepositoryService', true],
        ], [
            'projetRepository' => 'App\\Repository\\ProjetRepository',
            'technologieRepository' => 'App\\Repository\\TechnologieRepository',
            'demandeContactRepository' => 'App\\Repository\\DemandeContactRepository',
            'projetImageRepository' => 'App\\Repository\\ProjetImageRepository',
        ]))->withContext('App\\Controller\\AdminController::dashboard()', $container);
    }
}
