<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerlistContactRequestsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LHrctDy.App\Controller\Admin\ContactController::listContactRequests()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeContactRepository' => ['privates', 'App\\Repository\\DemandeContactRepository', 'getDemandeContactRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'demandeContactRepository' => 'App\\Repository\\DemandeContactRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\Admin\\ContactController::listContactRequests()', $container);

        if (isset($container->privates['.service_locator.LHrctDy.App\\Controller\\Admin\\ContactController::listContactRequests()'])) {
            return $container->privates['.service_locator.LHrctDy.App\\Controller\\Admin\\ContactController::listContactRequests()'];
        }

        return $container->privates['.service_locator.LHrctDy.App\\Controller\\Admin\\ContactController::listContactRequests()'] = $instance;
    }
}
