<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.B3PwOFX.App\Controller\Admin\ContactController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeContactRepository' => ['privates', 'App\\Repository\\DemandeContactRepository', 'getDemandeContactRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demandeContactRepository' => 'App\\Repository\\DemandeContactRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\ContactController::delete()', $container);

        if (isset($container->privates['.service_locator.B3PwOFX.App\\Controller\\Admin\\ContactController::delete()'])) {
            return $container->privates['.service_locator.B3PwOFX.App\\Controller\\Admin\\ContactController::delete()'];
        }

        return $container->privates['.service_locator.B3PwOFX.App\\Controller\\Admin\\ContactController::delete()'] = $instance;
    }
}
