<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7J_EGIL.App\Controller\Admin\ContactController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7J_EGIL.App\\Controller\\Admin\\ContactController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeContactRepository' => ['privates', 'App\\Repository\\DemandeContactRepository', 'getDemandeContactRepositoryService', true],
        ], [
            'demandeContactRepository' => 'App\\Repository\\DemandeContactRepository',
        ]))->withContext('App\\Controller\\Admin\\ContactController::show()', $container);
    }
}
