<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeContactRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DemandeContactRepository' shared autowired service.
     *
     * @return \App\Repository\DemandeContactRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DemandeContactRepository'] = new \App\Repository\DemandeContactRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
