<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalerieControllerdeleteImageService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Kq27LHM.App\Controller\Admin\GalerieController::deleteImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Kq27LHM'] ?? $container->load('get_ServiceLocator_Kq27LHMService'));

        if (isset($container->privates['.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()'])) {
            return $container->privates['.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\GalerieController::deleteImage()', $container);

        if (isset($container->privates['.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()'])) {
            return $container->privates['.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()'];
        }

        return $container->privates['.service_locator.Kq27LHM.App\\Controller\\Admin\\GalerieController::deleteImage()'] = $instance;
    }
}
