<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalerieControllergalerieService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zvDKqz1.App\Controller\Admin\GalerieController::galerie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetImageRepository' => ['privates', 'App\\Repository\\ProjetImageRepository', 'getProjetImageRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'projetImageRepository' => 'App\\Repository\\ProjetImageRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\GalerieController::galerie()', $container);

        if (isset($container->privates['.service_locator.zvDKqz1.App\\Controller\\Admin\\GalerieController::galerie()'])) {
            return $container->privates['.service_locator.zvDKqz1.App\\Controller\\Admin\\GalerieController::galerie()'];
        }

        return $container->privates['.service_locator.zvDKqz1.App\\Controller\\Admin\\GalerieController::galerie()'] = $instance;
    }
}
