<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalerieControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BIGH6bh.App\Controller\Admin\GalerieController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BIGH6bh.App\\Controller\\Admin\\GalerieController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetImageRepository' => ['privates', 'App\\Repository\\ProjetImageRepository', 'getProjetImageRepositoryService', true],
        ], [
            'projetImageRepository' => 'App\\Repository\\ProjetImageRepository',
        ]))->withContext('App\\Controller\\Admin\\GalerieController::index()', $container);
    }
}
