<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllergalerieService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5XBlwc3.App\Controller\HomeController::galerie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5XBlwc3.App\\Controller\\HomeController::galerie()'] = ($container->privates['.service_locator.5XBlwc3'] ?? $container->load('get_ServiceLocator_5XBlwc3Service'))->withContext('App\\Controller\\HomeController::galerie()', $container);
    }
}
