<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerprojectsxService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Kui3vX1.App\Controller\HomeController::projectsx()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kui3vX1.App\\Controller\\HomeController::projectsx()'] = ($container->privates['.service_locator.Kui3vX1'] ?? $container->load('get_ServiceLocator_Kui3vX1Service'))->withContext('App\\Controller\\HomeController::projectsx()', $container);
    }
}
