<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerskillsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ILz2ZmF.App\Controller\HomeController::skills()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ILz2ZmF.App\\Controller\\HomeController::skills()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'technologieRepository' => ['privates', 'App\\Repository\\TechnologieRepository', 'getTechnologieRepositoryService', true],
        ], [
            'technologieRepository' => 'App\\Repository\\TechnologieRepository',
        ]))->withContext('App\\Controller\\HomeController::skills()', $container);
    }
}
