<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageProjetTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ImageProjetType' shared autowired service.
     *
     * @return \App\Form\ImageProjetType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ImageProjetType'] = new \App\Form\ImageProjetType();
    }
}
