<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllerlistService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..tj0HNa.App\Controller\Admin\ProjectController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'projetRepository' => 'App\\Repository\\ProjetRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\Admin\\ProjectController::list()', $container);

        if (isset($container->privates['.service_locator..tj0HNa.App\\Controller\\Admin\\ProjectController::list()'])) {
            return $container->privates['.service_locator..tj0HNa.App\\Controller\\Admin\\ProjectController::list()'];
        }

        return $container->privates['.service_locator..tj0HNa.App\\Controller\\Admin\\ProjectController::list()'] = $instance;
    }
}
