<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProjectType' shared autowired service.
     *
     * @return \App\Form\ProjectType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProjectType'] = new \App\Form\ProjectType();
    }
}
