<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rDySncO.App\Controller\Admin\ProjectController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.rDySncO'] ?? $container->load('get_ServiceLocator_RDySncOService'));

        if (isset($container->privates['.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()'])) {
            return $container->privates['.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\ProjectController::delete()', $container);

        if (isset($container->privates['.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()'])) {
            return $container->privates['.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()'];
        }

        return $container->privates['.service_locator.rDySncO.App\\Controller\\Admin\\ProjectController::delete()'] = $instance;
    }
}
