<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.rDySncO.App\Entity\Projet' shared service.
     *
     * @return \App\Entity\Projet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rDySncO": it needs an instance of "App\\Entity\\Projet" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
