<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechnologyControllerdeleteTechnologyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.foA9oWh.App\Controller\Admin\TechnologyController::deleteTechnology()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'technologie' => ['privates', '.errored..service_locator.foA9oWh.App\\Entity\\Technologie', NULL, 'Cannot autowire service ".service_locator.foA9oWh": it needs an instance of "App\\Entity\\Technologie" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'technologie' => 'App\\Entity\\Technologie',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Admin\\TechnologyController::deleteTechnology()', $container);

        if (isset($container->privates['.service_locator.foA9oWh.App\\Controller\\Admin\\TechnologyController::deleteTechnology()'])) {
            return $container->privates['.service_locator.foA9oWh.App\\Controller\\Admin\\TechnologyController::deleteTechnology()'];
        }

        return $container->privates['.service_locator.foA9oWh.App\\Controller\\Admin\\TechnologyController::deleteTechnology()'] = $instance;
    }
}
