<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechnologyControllerlistTechnologiesService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zQk5dmt.App\Controller\Admin\TechnologyController::listTechnologies()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'technologieRepository' => ['privates', 'App\\Repository\\TechnologieRepository', 'getTechnologieRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'technologieRepository' => 'App\\Repository\\TechnologieRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\Admin\\TechnologyController::listTechnologies()', $container);

        if (isset($container->privates['.service_locator.zQk5dmt.App\\Controller\\Admin\\TechnologyController::listTechnologies()'])) {
            return $container->privates['.service_locator.zQk5dmt.App\\Controller\\Admin\\TechnologyController::listTechnologies()'];
        }

        return $container->privates['.service_locator.zQk5dmt.App\\Controller\\Admin\\TechnologyController::listTechnologies()'] = $instance;
    }
}
