<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechnologieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TechnologieRepository' shared autowired service.
     *
     * @return \App\Repository\TechnologieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TechnologieRepository'] = new \App\Repository\TechnologieRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
