<?php

namespace ContainerHHIce99;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCreateTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UserCreateType' shared autowired service.
     *
     * @return \App\Form\UserCreateType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserCreateType'] = new \App\Form\UserCreateType();
    }
}
