<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \App\Entity\Projet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null, 16],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null, 16],
        "\0".parent::class."\0".'githubLinks' => [parent::class, 'githubLinks', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'lien' => [parent::class, 'lien', null, 16],
        "\0".parent::class."\0".'projetImages' => [parent::class, 'projetImages', null, 16],
        "\0".parent::class."\0".'technologies' => [parent::class, 'technologies', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'typeProjet' => [parent::class, 'typeProjet', null, 16],
        "\0".parent::class."\0".'visible' => [parent::class, 'visible', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'documents' => [parent::class, 'documents', null, 16],
        'etat' => [parent::class, 'etat', null, 16],
        'githubLinks' => [parent::class, 'githubLinks', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'lien' => [parent::class, 'lien', null, 16],
        'projetImages' => [parent::class, 'projetImages', null, 16],
        'technologies' => [parent::class, 'technologies', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'typeProjet' => [parent::class, 'typeProjet', null, 16],
        'visible' => [parent::class, 'visible', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
